services:
  pt-supermercado_db:
    image: postgres:16
    container_name: pt-supermercado_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pt-supermercado_data:/var/lib/postgresql/data
   
volumes:
  pt-supermercado_data: {}
