apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/soydz/pt-supermercado
    targetRevision: main
    path: k8s/api

  destination:
    server: https://kubernetes.default.svc
    namespace: pt-supermercado

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
